FROM alpine:latest

LABEL org.opencontainers.image.authors="Kura"
LABEL org.opencontainers.image.title="curl with openssl 4 for ECH support, http2, and http3"
LABEL org.opencontainers.image.source="https://git.kura.gg/kura/forgejo"
LABEL org.opencontainers.image.url="https://git.kura.gg/kura/forgejo/src/branch/main/data/curl"

ENV OPENSSL_VERSION=4.0.0
ENV CURL_VERSION=8.19.0
ENV NGTCP2_VERSION=1.22.1
ENV NGHTTP2_VERSION=1.69.0
ENV NGHTTP3_VERSION=1.15.0

RUN set -x \
    && apk add --no-cache --virtual .runtime-deps \
        ca-certificates-bundle \
        musl \
        zlib \
        brotli-libs \
        zstd-libs \
        c-ares \
        libidn2 \
        libpsl \
    && apk add --no-cache --virtual .build-deps \
        autoconf \
        automake \
        libtool \
        make \
        perl \
        gcc \
        bash \
        linux-headers \
        libc-dev \
        zlib-dev \
        clang-libclang \
        brotli-dev \
        zstd-dev \
        c-ares-dev \
        libidn2-dev \
        libpsl-dev \
    && tempDir=$(mktemp -d) \
    && cd ${tempDir} \
    && wget -O openssl-${OPENSSL_VERSION}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz \
    && wget -O curl-${CURL_VERSION}.tar.gz https://github.com/curl/curl/releases/download/curl-$(echo "${CURL_VERSION}" | sed 's/\./_/g')/curl-${CURL_VERSION}.tar.gz \
    && wget -O nghttp2-${NGHTTP2_VERSION}.tar.gz https://github.com/nghttp2/nghttp2/releases/download/v${NGHTTP2_VERSION}/nghttp2-${NGHTTP2_VERSION}.tar.gz \
    && wget -O nghttp3-${NGHTTP3_VERSION}.tar.gz https://github.com/ngtcp2/nghttp3/releases/download/v${NGHTTP3_VERSION}/nghttp3-${NGHTTP3_VERSION}.tar.gz \
    && wget -O ngtcp2-${NGTCP2_VERSION}.tar.gz https://github.com/ngtcp2/ngtcp2/releases/download/v${NGTCP2_VERSION}/ngtcp2-${NGTCP2_VERSION}.tar.gz \
    && mkdir openssl-${OPENSSL_VERSION} \
        curl-${CURL_VERSION} \
        nghttp2-${NGHTTP2_VERSION} \
        nghttp3-${NGHTTP3_VERSION} \
        ngtcp2-${NGTCP2_VERSION} \
    && tar xvzf openssl-${OPENSSL_VERSION}.tar.gz -C "openssl-${OPENSSL_VERSION}" --strip-components 1 \
    && tar xvzf curl-${CURL_VERSION}.tar.gz -C "curl-${CURL_VERSION}" --strip-components 1 \
    && tar xvzf nghttp2-${NGHTTP2_VERSION}.tar.gz -C "nghttp2-${NGHTTP2_VERSION}" --strip-components 1 \
    && tar xvzf nghttp3-${NGHTTP3_VERSION}.tar.gz -C "nghttp3-${NGHTTP3_VERSION}" --strip-components 1 \
    && tar xvzf ngtcp2-${NGTCP2_VERSION}.tar.gz -C "ngtcp2-${NGTCP2_VERSION}" --strip-components 1 \
    && cd ${tempDir}/openssl-${OPENSSL_VERSION} \
    && ./Configure \
        --prefix=/usr \
        --libdir=lib \
        --openssldir=/etc/ssl \
        enable-ktls \
        shared \
        enable-zlib-dynamic \
        enable-brotli-dynamic \
        enable-zstd-dynamic \
        no-async \
        no-comp \
        no-idea \
        no-mdc2 \
        no-rc5 \
        no-ec2m \
        no-seed \
        no-weak-ssl-ciphers \
        no-docs \
        no-tests \
        no-ssl3 \
        no-tls1 \
        no-tls1_1 \
        -O3 -g -pipe -Wa,--noexecstack \
    && make -j$(nproc) \
    && make install_sw \
    && cd ${tempDir}/nghttp2-${NGHTTP2_VERSION} \
    && ./configure --prefix=/usr --enable-lib-only \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/nghttp3-${NGHTTP3_VERSION} \
    && autoreconf -i \
    && ./configure --prefix=/usr --enable-lib-only \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/ngtcp2-${NGTCP2_VERSION} \
    && autoreconf -i \
    && ./configure --prefix=/usr --enable-lib-only \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/curl-${CURL_VERSION} \
    && ./configure \
        --prefix=/usr \
        --enable-ares \
        --enable-ipv6 \
        --enable-unix-sockets \
        --enable-alt-svc \
        --enable-static \
        --disable-shared \
        --enable-ech \
        --enable-doh \
        --with-libidn2 \
        --with-zlib \
        --with-brotli \
        --with-zstd \
        --with-nghttp2 \
        --with-nghttp3 \
        --with-ngtcp2 \
        --with-openssl \
        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
        --with-ca-path=/etc/ssl/certs \
        --disable-ldap \
        --with-pic \
        --enable-websockets \
        --without-libssh2 \
    && make -j$(nproc) \
    && make install \
    && apk del --no-network .build-deps \
    && rm -rf ${tempDir}

CMD ["curl"]
