#!/usr/bin/bash
if ! command -v jq > /dev/null || ! command -v curl > /dev/null; then echo "Please install curl and jq" && exit 1; fi
if [ "$#" -ne 1 ]; then echo "Containerfile param required" && exit 1; fi
CONTAINERFILE=$1

openssl=$(curl -s https://api.github.com/repos/openssl/openssl/releases 2>&1 /dev/null | \
          jq -r '.[0].tag_name' | \
          cut -d'v' -f 2 | \
          tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

curl=$(curl -s https://api.github.com/repos/curl/curl/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

nghttp2=$(curl -s https://api.github.com/repos/nghttp2/nghttp2/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

nghttp3=$(curl -s https://api.github.com/repos/ngtcp2/nghttp3/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

ngtcp2=$(curl -s https://api.github.com/repos/ngtcp2/ngtcp2/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

echo "openssl=$openssl"
echo "curl=$curl"
echo "nghttp2=$nghttp2"
echo "nghttp3=$nghttp3"
echo "ngtcp2=$ngtcp2"

sed -i \
    -re "s/(ENV=OPENSSL_VERSION)\ .*/\1 $openssl/g" \
    -re "s/(ENV=CURL_VERSION)\ .*/\1 $curl/g" \
    -re "s/(ENV=NGTCP2_VERSION)\ .*/\1 $nghttp2/g" \
    -re "s/(ENV=NGHTTP2_VERSION)\ .*/\1 $nghttp3/g" \
    -re "s/(ENV=NGHTTP3_VERSION)\ .*/\1 $ngtcp2/g" \
    "$CONTAINERFILE"
