FROM codeberg.org/forgejo/forgejo:a.b.c

RUN apk --no-cache add \
    asciidoctor \
    freetype \
    freetype-dev \
    gcc \
    g++ \
    libpng \
    libffi-dev \
    pandoc \
    python3-dev \
    py3-pyzmq \
    py3-pip \
    py3-wheel \
    && \
    rm -rf /var/cache/apk/*

RUN python3 -m pip install --no-input --break-system-packages --root-user-action=ignore \
    jupyter \
    docutils \
    && \
    rm -rf /root/.cache
