FROM codeberg.org/forgejo/forgejo:12.0.2

RUN apk --no-cache add \
    asciidoctor \
    freetype \
    freetype-dev \
    gcc \
    g++ \
    libpng \
    libffi-dev \
    pandoc \
    python3-dev \
    py3-pyzmq \
    pipx \
    && \
    rm -rf /var/cache/apk/*
RUN pipx install \
    jupyter \
    docutils \
    --include-deps --global \
    && \
    rm -rf /root/.cache
