FROM nginx:mainline-alpine-slim

RUN apk --no-cache add \
    openssl \
    curl \
    ca-certificates

RUN printf "@nginx http://nginx.org/packages/mainline/alpine/%s/main" \
    "v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)" \
    >> /etc/apk/repositories

RUN curl -o /etc/apk/keys/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub

RUN apk --no-cache add \
    nginx-module-acme@nginx \
    && \
    rm -rf /var/cache/apk/*
