FROM nginx:mainline-alpine-slim

RUN apk --no-cache add \
    openssl \
    curl \
    ca-certificates

RUN printf "%s%s%s%s\n" \
    "@nginx " \
    "http://nginx.org/packages/mainline/alpine/v" \
    $(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release) \
    "/main" \
    >> /etc/apk/repositories

RUN curl -o /etc/apk/keys/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub

RUN apk --no-cache add \
    nginx-module-acme@nginx \
    && \
    rm -rf /var/cache/apk/*
