FROM nginx:mainline-alpine-slim

LABEL org.opencontainers.image.authors="Kura"
LABEL org.opencontainers.image.source="https://git.kura.gg/kura/forgejo"
LABEL org.opencontainers.image.url="https://git.kura.gg/kura/forgejo/src/branch/main/data/nginx"

ENV OPENSSL_VERSION=4.0.0
ENV NGINX_VERSION=1.30.0
ENV LUAJIT_VERSION=2.1-20250826
ENV BROTLI_VERSION=1.0.0
ENV ZSTD_VERSION=0.1.1
ENV ACME_VERSION=0.4.0
ENV NAXSI_VERSION=1.7
ENV NDK_VERSION=0.3.4
ENV NGX_LUA_VERSION=0.10.29
ENV NGX_VTS_VERSION=0.2.5
ENV LUA_RESTY_CORE_VERSION=0.1.32
ENV LUA_RESTY_LRU_VERSION=0.15

RUN set -x \
    && apk del nginx* \
    && apk add --no-cache --virtual .runtime-deps \
        curl \
        libgcc \
        musl \
        pcre2 \
        zlib \
        brotli-libs \
        zstd-libs \
    && apk add --no-cache --virtual .build-deps \
        make \
        perl \
        alpine-sdk \
        gcc \
        libc-dev \
        pcre2-dev \
        zlib-dev \
        linux-headers \
        bash \
        cargo \
        clang-libclang \
        brotli-dev \
        zstd-dev \
    && tempDir=$(mktemp -d) \
    && cd ${tempDir} \
    && curl -L \
        -o openssl-${OPENSSL_VERSION}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz \
        -o nginx-${NGINX_VERSION}.tar.gz https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
        -o luajit-${LUAJIT_VERSION}.tar.gz https://github.com/openresty/luajit2/archive/refs/tags/v${LUAJIT_VERSION}.tar.gz \
        -o ngx-brotli-${BROTLI_VERSION}.tar.gz https://github.com/google/ngx_brotli/archive/refs/tags/v${BROTLI_VERSION}rc.tar.gz \
        -o ngx-zstd-${ZSTD_VERSION}.tar.gz https://github.com/tokers/zstd-nginx-module/archive/refs/tags/${ZSTD_VERSION}.tar.gz \
        -o ngx-acme-${ACME_VERSION}.tar.gz https://github.com/nginx/nginx-acme/releases/download/v${ACME_VERSION}/nginx-acme-${ACME_VERSION}.tar.gz \
        -o ngx-naxsi-${NAXSI_VERSION}.tar.gz https://github.com/wargio/naxsi/releases/download/${NAXSI_VERSION}/naxsi-${NAXSI_VERSION}-src-with-deps.tar.gz \
        -o ngx-dev-kit-${NDK_VERSION}.tar.gz https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v${NDK_VERSION}.tar.gz \
        -o ngx-lua-${NGX_LUA_VERSION}.tar.gz https://github.com/openresty/lua-nginx-module/archive/refs/tags/v${NGX_LUA_VERSION}.tar.gz \
        -o ngx-vts-${NGX_VTS_VERSION}.tar.gz https://github.com/vozlt/nginx-module-vts/archive/refs/tags/v${NGX_VTS_VERSION}.tar.gz \
        -o lua-resty-core-${LUA_RESTY_CORE_VERSION}.tar.gz https://github.com/openresty/lua-resty-core/archive/refs/tags/v${LUA_RESTY_CORE_VERSION}.tar.gz \
        -o lua-resty-lru-${LUA_RESTY_LRU_VERSION}.tar.gz https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v${LUA_RESTY_LRU_VERSION}.tar.gz \
        -o ngx_dynamic_tls_records_1.29.patch https://raw.githubusercontent.com/nginx-modules/ngx_http_tls_dyn_size/refs/heads/master/nginx__dynamic_tls_records_1.29.2%2B.patch \
    && mkdir \
        openssl-${OPENSSL_VERSION} \
        nginx-${NGINX_VERSION} \
        luajit-${LUAJIT_VERSION} \
        ngx-brotli-${BROTLI_VERSION} \
        ngx-zstd-${ZSTD_VERSION} \
        ngx-acme-${ACME_VERSION} \
        ngx-naxsi-${NAXSI_VERSION} \
        ngx-dev-kit-${NDK_VERSION} \
        ngx-lua-${NGX_LUA_VERSION} \
        ngx-vts-${NGX_VTS_VERSION} \
        lua-resty-core-${LUA_RESTY_CORE_VERSION} \
        lua-resty-lru-${LUA_RESTY_LRU_VERSION} \
    && tar xvzf openssl-${OPENSSL_VERSION}.tar.gz -C "openssl-${OPENSSL_VERSION}" --strip-components 1 \
    && tar xvzf nginx-${NGINX_VERSION}.tar.gz -C "nginx-${NGINX_VERSION}" --strip-components 1 \
    && tar xvzf luajit-${LUAJIT_VERSION}.tar.gz -C "luajit-${LUAJIT_VERSION}" --strip-components 1 \
    && tar xvzf ngx-brotli-${BROTLI_VERSION}.tar.gz -C "ngx-brotli-${BROTLI_VERSION}" --strip-components 1 \
    && tar xvzf ngx-zstd-${ZSTD_VERSION}.tar.gz -C "ngx-zstd-${ZSTD_VERSION}" --strip-components 1 \
    && tar xvzf ngx-acme-${ACME_VERSION}.tar.gz -C "ngx-acme-${ACME_VERSION}" --strip-components 1 \
    && tar xvzf ngx-naxsi-${NAXSI_VERSION}.tar.gz -C "ngx-naxsi-${NAXSI_VERSION}" \
    && tar xvzf ngx-dev-kit-${NDK_VERSION}.tar.gz -C "ngx-dev-kit-${NDK_VERSION}" --strip-components 1 \
    && tar xvzf ngx-lua-${NGX_LUA_VERSION}.tar.gz -C "ngx-lua-${NGX_LUA_VERSION}" --strip-components 1 \
    && tar xvzf ngx-vts-${NGX_VTS_VERSION}.tar.gz -C "ngx-vts-${NGX_VTS_VERSION}" --strip-components 1 \
    && tar xvzf lua-resty-core-${LUA_RESTY_CORE_VERSION}.tar.gz -C "lua-resty-core-${LUA_RESTY_CORE_VERSION}" --strip-components 1 \
    && tar xvzf lua-resty-lru-${LUA_RESTY_LRU_VERSION}.tar.gz -C "lua-resty-lru-${LUA_RESTY_LRU_VERSION}" --strip-components 1 \
    && cd ${tempDir}/openssl-${OPENSSL_VERSION} \
    && ./Configure \
        --prefix=/usr \
        --libdir=lib \
        --openssldir=/etc/ssl \
        enable-ktls \
        shared \
        enable-zlib-dynamic \
        enable-brotli-dynamic \
        enable-zstd-dynamic \
        no-async \
        no-comp \
        no-idea \
        no-mdc2 \
        no-rc5 \
        no-ec2m \
        no-seed \
        no-weak-ssl-ciphers \
        no-docs \
        no-tests \
        no-ssl3 \
        no-tls1 \
        no-tls1_1 \
        -O3 -g -pipe -Wa,--noexecstack \
    && make -j$(nproc) \
    && make install_sw \
    && cd ${tempDir}/luajit-${LUAJIT_VERSION} \
    && sed -i 's/export PREFIX= \/usr\/local/export PREFIX=\/usr/g' Makefile \
    && make -j$(nproc) \
    && make install \
    && rm ${tempDir}/ngx-acme-${ACME_VERSION}/Cargo.lock \
    && sed -i 's/openssl = { version = "0.10.74"/openssl = { version = "0.10.78"/g;s/openssl-sys = { version = "0.9.110"/openssl-sys = { version = "0.9.114"/g' ${tempDir}/ngx-acme-${ACME_VERSION}/Cargo.toml \
    && cd ${tempDir}/nginx-${NGINX_VERSION} \
    && patch -p1 < ${tempDir}/ngx_dynamic_tls_records_1.29.patch \
    && export LUAJIT_LIB=/usr/lib \
    && export LUAJIT_INC=/usr/include/luajit-2.1 \
    && ./configure \
        --prefix=/etc/nginx \
        --sbin-path=/usr/sbin/nginx \
        --modules-path=/usr/lib/nginx/modules \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --pid-path=/run/nginx.pid \
        --lock-path=/run/nginx.lock \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --user=nginx \
        --group=nginx \
        --with-debug \
        --with-compat \
        --with-file-aio \
        --with-threads \
        --with-http_gzip_static_module \
        --with-http_realip_module \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_sub_module \
        --with-http_v2_module \
        --with-http_v3_module \
        --with-stream \
        --with-stream_realip_module \
        --with-stream_ssl_module \
        --with-stream_ssl_preread_module \
        --add-module=${tempDir}/ngx-brotli-${BROTLI_VERSION} \
        --add-module=${tempDir}/ngx-zstd-${ZSTD_VERSION} \
        --add-module=${tempDir}/ngx-acme-${ACME_VERSION} \
        --add-module=${tempDir}/ngx-naxsi-${NAXSI_VERSION}/naxsi_src \
        --add-module=${tempDir}/ngx-dev-kit-${NDK_VERSION} \
        --add-module=${tempDir}/ngx-lua-${NGX_LUA_VERSION} \
        --add-module=${tempDir}/ngx-vts-${NGX_VTS_VERSION} \
        --with-ld-opt='-Wl,-rpath,/usr/lib/luajit' \
        --with-cc-opt='-O3 -g -pipe -Wall' \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/lua-resty-core-${LUA_RESTY_CORE_VERSION} \
    && make install PREFIX=/usr \
    && cd ${tempDir}/lua-resty-lru-${LUA_RESTY_LRU_VERSION} \
    && make install PREFIX=/usr \
    && curl -sL https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt | \
        grep -v Disallow | \
        cut -d' ' -f2 | \
        tr '[:upper:]' '[:lower:]' | \
        while read u; do echo "~*$u* 1;" >> /etc/nginx/ai-ua.map; done \
    && mv ${tempDir}/ngx-naxsi-${NAXSI_VERSION}/naxsi_rules /etc/nginx/naxsi \
    && rm -rf /etc/nginx/conf.d \
        /etc/nginx/fastcgi* \
        /etc/nginx/html \
        /etc/nginx/koi* \
        /etc/nginx/*.default \
        /etc/nginx/scgi* \
        /etc/nginx/uwsgi* \
        /etc/nginx/win-utf \
    && apk del --no-network .build-deps \
    && rm -rf ${tempDir}
