FROM nginx:mainline-alpine-slim

ENV OPENSSL_VERSION 4.0.0
ENV NGINX_VERSION 1.30.0
ENV BROTLI_VERSION 1.0.0
ENV ZSTD_VERSION 0.1.1
ENV ACME_VERSION 0.3.1
ENV NAXSI_VERSION 1.7
ENV LUAJIT_VERSION 2.1-20250826
ENV NDK_VERSION 0.3.4
ENV NGX_LUA_VERSION 0.10.29
ENV LUA_RESTY_CORE_VERSION 0.1.32
ENV LUA_RESTY_LRU_VERSION 0.15

RUN apk add --no-cache --virtual .runtime-deps \
        curl \
        libgcc \
        musl \
        pcre2 \
        zlib \
        brotli-libs \
        zstd-libs \
    && apk add --no-cache --virtual .build-deps \
        perl \
        alpine-sdk \
        gcc \
        libc-dev \
        make \
        pcre2-dev \
        zlib-dev \
        linux-headers \
        bash \
        cargo \
        clang-libclang \
        brotli-dev \
        zstd-dev \
    && set -x \
    && tempDir=$(mktemp -d) \
    && cd ${tempDir} \
    && curl -L \
        -o openssl-${OPENSSL_VERSION}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz \
        -o nginx-${NGINX_VERSION}.tar.gz https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
        -o brotli-${BROTLI_VERSION}.tar.gz https://github.com/google/ngx_brotli/archive/refs/tags/v${BROTLI_VERSION}rc.tar.gz \
        -o zstd-${ZSTD_VERSION}.tar.gz https://github.com/tokers/zstd-nginx-module/archive/refs/tags/${ZSTD_VERSION}.tar.gz \
        -o acme-${ACME_VERSION}.tar.gz https://github.com/nginx/nginx-acme/releases/download/v${ACME_VERSION}/nginx-acme-${ACME_VERSION}.tar.gz \
        -o naxsi-${NAXSI_VERSION}.tar.gz https://github.com/wargio/naxsi/releases/download/${NAXSI_VERSION}/naxsi-${NAXSI_VERSION}-src-with-deps.tar.gz \
        -o ngx_dynamic_tls_records_1.29.patch https://raw.githubusercontent.com/nginx-modules/ngx_http_tls_dyn_size/refs/heads/master/nginx__dynamic_tls_records_1.29.2%2B.patch \
        -o luajit-${LUAJIT_VERSION}.tar.gz https://github.com/openresty/luajit2/archive/refs/tags/v${LUAJIT_VERSION}.tar.gz \
        -o ndk-${NDK_VERSION}.tar.gz https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v${NDK_VERSION}.tar.gz \
        -o ngx_lua-${NGX_LUA_VERSION}.tar.gz https://github.com/openresty/lua-nginx-module/archive/refs/tags/v${NGX_LUA_VERSION}.tar.gz \
        -o lua-resty-core-${LUA_RESTY_CORE_VERSION}.tar.gz https://github.com/openresty/lua-resty-core/archive/refs/tags/v${LUA_RESTY_CORE_VERSION}.tar.gz \
        -o lua-resty-lru-${LUA_RESTY_LRU_VERSION}.tar.gz https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v${LUA_RESTY_LRU_VERSION}.tar.gz \
    && cat ${tempDir}/*.tar.gz | tar xvzf - -i \
    && cd ${tempDir}/openssl-${OPENSSL_VERSION} \
    && perl ./Configure \
        --prefix=/usr \
        --libdir=lib \
        --openssldir=/etc/ssl \
        enable-fips \
        enable-ktls \
        shared \
        no-zlib \
        no-async \
        no-comp \
        no-idea \
        no-mdc2 \
        no-rc5 \
        no-ec2m \
        no-ssl3 \
        no-seed \
        no-weak-ssl-ciphers \
        no-docs \
        no-tests \
        -O3 -g -pipe -Wa,--noexecstack \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/luajit2-${LUAJIT_VERSION} \
    && sed -i 's/export PREFIX= \/usr\/local/export PREFIX=\/usr/g' Makefile \
    && make -j$(nproc) \
    && make install \
    && rm ${tempDir}/nginx-acme-${ACME_VERSION}/Cargo.lock \
    && sed -i 's|openssl = { version = "0.10.74"|openssl = { git = "https://github.com/rust-openssl/rust-openssl.git"|g;s|openssl-sys = { version = "0.9.110"|openssl-sys = { git = "https://github.com/rust-openssl/rust-openssl.git"|g' ${tempDir}/nginx-acme-${ACME_VERSION}/Cargo.toml \
    && cd ${tempDir}/nginx-${NGINX_VERSION} \
    && patch -p1 < ${tempDir}/ngx_dynamic_tls_records_1.29.patch \
    && export LUAJIT_LIB=/usr/lib \
    && export LUAJIT_INC=/usr/include/luajit-2.1 \
    && ls ${tempDir}/ \
    && ./configure \
        --prefix=/etc/nginx \
        --sbin-path=/usr/sbin/nginx \
        --modules-path=/usr/lib/nginx/modules \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --pid-path=/run/nginx.pid \
        --lock-path=/run/nginx.lock \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --user=nginx \
        --group=nginx \
        --with-compat \
        --with-file-aio \
        --with-threads \
        --with-http_gzip_static_module \
        --with-http_realip_module \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_sub_module \
        --with-http_v2_module \
        --with-http_v3_module \
        --with-stream \
        --with-stream_realip_module \
        --with-stream_ssl_module \
        --with-stream_ssl_preread_module \
        --add-module=${tempDir}/ngx_brotli-${BROTLI_VERSION}rc \
        --add-module=${tempDir}/zstd-nginx-module-${ZSTD_VERSION} \
        --add-module=${tempDir}/nginx-acme-${ACME_VERSION} \
        --add-module=${tempDir}/naxsi_src \
        --add-module=${tempDir}/ngx_devel_kit-${NDK_VERSION} \
        --add-module=${tempDir}/lua-nginx-module-${NGX_LUA_VERSION} \
        --with-ld-opt='-Wl,-rpath,/usr/lib/luajit' \
        --with-cc-opt='-O3 -g -pipe -Wall' \
    && make -j$(nproc) \
    && make install \
    && cd ${tempDir}/lua-resty-core-${LUA_RESTY_CORE_VERSION} \
    && make install PREFIX=/usr \
    && cd ${tempDir}/lua-resty-lrucache-${LUA_RESTY_LRU_VERSION} \
    && make install PREFIX=/usr \
    && curl -sL https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt | \
        grep -v Disallow | \
        cut -d' ' -f2 | \
        tr '[:upper:]' '[:lower:]' | \
        while read u; do echo "~*$u* 1;" >> /etc/nginx/ai-ua.map; done \
    && mv ${tempDir}/naxsi_rules /etc/nginx/naxsi \
    && rm -rf /etc/nginx/conf.d \
        /etc/nginx/fastcgi* \
        /etc/nginx/html \
        /etc/nginx/koi* \
        /etc/nginx/*.default \
        /etc/nginx/scgi* \
        /etc/nginx/uwsgi* \
        /etc/nginx/win-utf \
    && cd /  \
    && apk del --no-network .build-deps \
    && rm -rf ${tempDir}
