#!/usr/bin/bash
if ! command -v jq > /dev/null || ! command -v curl > /dev/null; then echo "Please install curl and jq" && exit 1; fi
version=$(curl -s https://api.github.com/repos/nginx/nginx-acme/releases | jq -r '.[0].tag_name' | cut -d'v' -f 2)
sed -i -re "s/(ENV ACME_VERSION)\ .*/\1 $version/gi" /data/nginx/Containerfile
