#!/usr/bin/bash
if ! command -v jq > /dev/null || ! command -v curl > /dev/null; then echo "Please install curl and jq" && exit 1; fi
if [ "$#" -ne 1 ]; then echo "Containerfile param required" && exit 1; fi
CONTAINERFILE=$1

openssl=$(curl -s https://api.github.com/repos/openssl/openssl/releases 2>&1 /dev/null | \
          jq -r '.[0].tag_name' | \
          cut -d'v' -f 2 | \
          tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

nginx=$(curl -s https://api.github.com/repos/nginx/nginx/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

luajit=$(curl -s https://api.github.com/repos/openresty/luajit2/releases | \
         jq -r '.[0].tag_name' | \
         cut -d'v' -f 2 | \
         tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

acme=$(curl -s https://api.github.com/repos/nginx/nginx-acme/releases | \
       jq -r '.[0].tag_name' | \
       cut -d'v' -f 2 | \
       tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

naxsi=$(curl -s https://api.github.com/repos/wargio/naxsi/releases | \
        jq -r '.[0].tag_name' | \
        cut -d'v' -f 2 | \
        tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

ndk=$(curl -s https://api.github.com/repos/vision5/ngx_devel_kit/releases | \
      jq -r '.[0].tag_name' | \
      cut -d'v' -f 2 | \
      tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

lua=$(curl -s https://api.github.com/repos/openresty/lua-nginx-module/tags | \
      jq -r '.[].name' | \
      grep -vi r | \
      cut -d'v' -f 2 | \
      tr -d '[:alpha:][=-=]' | \
      head -1)
if [ $? -eq 0 ]; then exit 0; fi

vts=$(curl -s https://api.github.com/repos/vozlt/nginx-module-vts/releases | \
      jq -r '.[0].tag_name' | \
      cut -d'v' -f 2 | \
      tr -d '[:alpha:][=-=]')
if [ $? -eq 0 ]; then exit 0; fi

resty_core=$(curl -s https://api.github.com/repos/openresty/lua-resty-core/tags | \
             jq -r '.[].name' | \
             grep -vi r | \
             cut -d'v' -f 2 | \
             tr -d '[:alpha:][=-=]' | \
             head -1)
if [ $? -eq 0 ]; then exit 0; fi

resty_lru=$(curl -s https://api.github.com/repos/openresty/lua-resty-lrucache/tags | \
            jq -r '.[].name' | \
            grep -vi r | \
            cut -d'v' -f 2 | \
            tr -d '[:alpha:][=-=]' | \
            head -1)
if [ $? -eq 0 ]; then exit 0; fi

sed -i \
    -re "s/(ENV OPENSSL_VERSION)\ .*/\1 $openssl/g" \
    -re "s/(ENV NGINX_VERSION)\ .*/\1 $nginx/g" \
    -re "s/(ENV ACME_VERSION)\ .*/\1 $acme/g" \
    -re "s/(ENV NAXSI_VERSION)\ .*/\1 $naxsi/g" \
    -re "s/(NDK_VERSION)\ .*/\1 $ndk/g" \
    -re "s/(NGX_LUA_VERSION)\ .*/\1 $lua/g" \
    -re "s/(NGX_VTX_VERSION)\ .*/\1 $vts/g" \
    -re "s/(LUA_RESTY_CORE_VERSION)\ .*/\1 $resty_core/g" \
    -re "s/(LUA_RESTY_LRU_VERSION)\ .*/\1 $resty_lru/g" \
    "$CONTAINERFILE"
