FROM codeberg.org/forgejo/forgejo:a.b.c

LABEL org.opencontainers.image.authors="Kura"
LABEL org.opencontainers.image.source="https://git.kura.gg/kura/forgejo"
LABEL org.opencontainers.image.url="https://git.kura.gg/kura/forgejo/src/branch/main/data/forgejo"

RUN apk --no-cache add \
        asciidoctor \
        freetype \
        freetype-dev \
        gcc \
        g++ \
        libpng \
        libffi-dev \
        pandoc \
        python3-dev \
        py3-pyzmq \
        py3-pip \
        py3-wheel \
    && python3 -m pip install --no-input --break-system-packages --root-user-action=ignore \
        jupyter \
        docutils \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache
